name: black turtle TCM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07917
title: 'the black turtle clinic exists in order to give you the opportunity to strengthen your connection to nature. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c2c2c'
    - '#070707'
    - '#dfdfdf'
    - '#7e7e7e'
  brandStrength: 0.5598678658716381
  lightness: 0.2920815299730748
  saturation: 0.1487466488033533
  rhythmicContrast: 0.9108020304702222
purpose: []
